name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
    - name: Build frontend and backend
      run: |
        npm run build:frontend
        npm run build:backend
    - name: Build Docker images
      run: |
        docker build -t enterprise-app-frontend ./frontend
        docker build -t enterprise-app-backend ./backend
    - name: Push Docker images
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push enterprise-app-frontend
        docker push enterprise-app-backend
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v3
      with:
        manifests: |
          ./k8s/deployment.yaml
        images: |
          enterprise-app-frontend:latest
          enterprise-app-backend:latest
    - name: Run security scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: enterprise-app-frontend:latest